#!/bin/bash
export IFS=$'\n'

CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
if [ $# -eq 0 ] ; then
	echo "Usage : ${CMDNAME} [directry] "
	exit 1
fi

TARGET_DIR_LIST=(${@// /})
##
EXTLIST=(
"mp4"
"mkv"
)

##
for TARGET_DIR in ${TARGET_DIR_LIST[@]}
do
	for EXT in ${EXTLIST[@]}
	do
		echo ${TARGET_DIR} ${EXT}
		for FILENAME in `find "${TARGET_DIR}" -name "*.${EXT}" | sort`
		do	       
			title_count=`exiftool "${FILENAME}" | grep Title | wc -l`
			if [ $title_count = "0" ] ;then
				title=`basename "${FILENAME}"`
				title=${title%%.${EXT}}
				echo "${FILENAME} title:${title}"
				exiftool "${FILENAME}" -title="${title}" || continue
				rm "${FILENAME}"_original
			fi 
		done
	done
done

