#!/bin/bash
export IFS=$'\n'
DATE=`date +%Y_%m_%d`

argv=("$@")
CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
NICE=19
TARGET_DIR="."
CRF=28
THREADS=$(( (`cat /proc/cpuinfo | grep processor | wc -l` +1) / 2))
PRESET_V=veryslow
AUDIO_BITRATE=192k

##
usage_exit() {
    echo "Usage : ${CMDNAME} [-n nicevalue] [-c crf value] [-d dirname]"
    exit 1
}

if [ $# -eq 0 ]; then
    usage_exit
fi

while getopts n:t:p:b:d:h OPT
do
    case $OPT in
        n) NICE=$OPTARG
                ;;
        t) THREADS=$OPTARG
                ;;
        p) PRESET_V=$OPTARG
                ;;
        b) AUDIO_BITRATE=$OPTARG
                ;;
        d) TARGET_DIR=$OPTARG
                ;;
        h) usage_exit
                ;;
        \?) usage_exit
                ;;
    esac
done
shift $(($OPTIND - 1))

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | grep -v mp4 | grep -v mkv | grep -v avi | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mp4"
"mov"
"avi.mp4"
"wmv.mp4"
"flv.mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"m4a"
"avi"
"AVI"
"MPG"
"MPEG"
"ts"
"TS"
"webm"
"m2ts"
"mkv"
)
EXTLIST+=($(echo "${EXTLIST[*]^^}" ))
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for EXT in ${EXTLIST[@]}
do
	for FILENAME in `find "${TARGET_DIR}" -name "*.${EXT}" | sort`
	do
		ls -l "${FILENAME}"
		FILENAME_H265="${FILENAME%.${EXT}}.h265.mp4"
		nice -n ${NICE} ffmpeg -hide_banner -y -i "${FILENAME}" -c:a copy -c:v libx265 -crf ${CRF} -tag:v hvc1  -threads ${THREADS} "${FILENAME_H265}" || continue
		ls -l "${FILENAME_H265}"
      		rm -f "${FILENAME}"
		mv "${FILENAME_H265}" "${FILENAME%.${EXT}}.mp4"
	done
done
