#!/bin/bash
export IFS=$'\n'
DATE=`date +%Y_%m_%d`

argv=("$@")
CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`
if [ ${_pcnt} -gt 1 ]; then
        echo "This script has been running now. proc : ${_pcnt}"
        exit 1
fi

NICE=19
TARGET_DIR="."

##
usage_exit() {
    echo "Usage : ${CMDNAME} [-n nicevalue] [-t thread count] [-d dirname]"
    exit 1
}

if [ $# -eq 0 ]; then
    usage_exit
fi

while getopts n:t:p:b:d:h OPT
do
    case $OPT in
        n) NICE=$OPTARG
                ;;
        t) THREADS=$OPTARG
                ;;
        d) TARGET_DIR=$OPTARG
                ;;
        h) usage_exit
                ;;
        \?) usage_exit
                ;;
    esac
done
shift $(($OPTIND - 1))

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | grep -v mp4 | grep -v mkv | grep -v avi | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mov"
"mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"m4a"
"avi"
"AVI"
"MPG"
"MPEG"
"ts"
"TS"
"webm"
"m2ts"
"mkv"
)
EXTLIST+=($(echo "${EXTLIST[*]^^}" ))
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for EXT in ${EXTLIST[@]}
do
        for FILENAME in `find "${TARGET_DIR}" -name "*.${EXT}" | sort`
        do
		WIDTH=`ffprobe -i ${FILENAME} -v error -select_streams v:0 -show_entries stream=width | head -n 2 | tail -n 1 | cut -d "=" -f 2` || continue
		if [[ ! "${WIDTH}" =~ ^[0-9]+$ ]]; then
			echo ${FILENAME}":"${WIDTH}": not width number."
			continue
		fi
		if [ $(( WIDTH )) -gt 1280 ] ; then
			BASENAME=${FILENAME##*/}
			nice -n ${NICE} ffmpeg -hide_banner -y -i ${FILENAME} -vf scale=1280:-1 -crf 23 -preset fast -maxrate 6M -bufsize 12M /tmp/${BASENAME} || continue
			/bin/cp -vf /tmp/${BASENAME} ${FILENAME} || continue
			/bin/rm -vf /tmp/${BASENAME} || continue
		fi
        done
done
